# Generated by Django 5.0 on 2024-01-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('tasks', models.ManyToManyField(to='Tasks.task')),
            ],
        ),
    ]
